/**
 * Dummy companies data
 */

export const companies = [
  {
    name: "Company 1",
    id: 1,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 2,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 3,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 4,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 5,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 6,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 7,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 8,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 9,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 10,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 11,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 12,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 13,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 14,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 15,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 16,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 17,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 18,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 19,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 20,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
  {
    name: "Company 1",
    id: 21,
    status: "Operating",
    category_code: "Software",
    area: "Country 1",
  },
];
